-- public.pelicula definition

-- Drop table

-- DROP TABLE public.pelicula;

CREATE TABLE public.pelicula (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	director varchar(50) NULL,
	fecha_estreno int4 NULL,
	genero varchar(20) NULL,
	titulo varchar(100) NULL,
	CONSTRAINT pelicula_pkey PRIMARY KEY (id)
);