-- public.generos definition

-- Drop table

-- DROP TABLE public.generos;

CREATE TABLE public.generos (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar NOT NULL,
	CONSTRAINT generos_pk PRIMARY KEY (id)
);


-- public.autores definition

-- Drop table

-- DROP TABLE public.autores;

CREATE TABLE public.autores (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar NOT NULL,
	CONSTRAINT directores_pk PRIMARY KEY (id)
);


-- public.usuario definition

-- Drop table

-- DROP TABLE public.usuario;

CREATE TABLE public.usuario (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	codigo varchar NOT NULL,
	fecha_alta timestamp NOT NULL,
	fecha_baja timestamp NULL,
	CONSTRAINT usuario_pk PRIMARY KEY (id)
);


-- public.perfil definition

-- Drop table

-- DROP TABLE public.perfil;

CREATE TABLE public.perfil (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	codigo varchar NOT NULL,
	descripcion varchar NOT NULL,
	CONSTRAINT perfil_pk PRIMARY KEY (id)
);


-- public.libros definition

-- Drop table

-- DROP TABLE public.libros;

CREATE TABLE public.libros (
	id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
	titulo varchar NOT NULL,
	isbn varchar NOT NULL,
	id_genero int4 NOT NULL,
	id_autor int4 NOT NULL,
	CONSTRAINT libros_pk PRIMARY KEY (id),
	CONSTRAINT libros_fk FOREIGN KEY (id_genero) REFERENCES public.generos(id),
	CONSTRAINT libros_fk2 FOREIGN KEY (id_autor) REFERENCES public.autores(id)
);


-- public.usuario_perfil definition

-- Drop table

-- DROP TABLE public.usuario_perfil;

CREATE TABLE public.usuario_perfil (
	id_usuario int4 NOT NULL,
	id_perfil int4 NOT NULL,
	CONSTRAINT usuario_perfil_pk PRIMARY KEY (id_usuario, id_perfil),
	CONSTRAINT usuario_perfil_fk FOREIGN KEY (id_usuario) REFERENCES public.usuario(id),
	CONSTRAINT usuario_perfil_fk_1 FOREIGN KEY (id_perfil) REFERENCES public.perfil(id)
);